import type { PropertyDetail } from '@/types/property';

export const mockPropertyDetails: PropertyDetail[] = [
    {
        id: '0194d3c4-9c02-7a56-8e5a-736021480112',
        title: 'Solar-powered retreat',
        location: 'Joshua Tree, California',
        imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=800&fit=crop',
        imageAlt: 'Luxurious wooden cabin with pool in Joshua Tree desert landscape',
        pricePerNight: 245,
        rating: 4.98,
        dates: 'Oct 22 – 27',
        images: [
            'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&h=800&fit=crop',
            'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
        ],
        description:
            'Escape to this solar-powered sanctuary nestled in the heart of Joshua Tree. This retreat offers a perfect blend of high-desert beauty and modern eco-luxury. Powered entirely by the sun, you can enjoy a completely off-grid experience without sacrificing comfort.\n\nWake up to panoramic views of the Mojave landscape. The house features floor-to-ceiling windows, reclaimed wood finishes, and a private pool that blends into the natural rock formations.',
        reviewCount: 48,
        propertyType: 'Entire cabin',
        bedrooms: 2,
        bathrooms: 1,
        beds: 2,
        maxGuests: 4,
        amenities: [
            { id: 1, name: 'Solar Energy', icon: 'Zap', category: 'essentials', available: true },
            { id: 2, name: 'Private Pool', icon: 'Waves', category: 'features', available: true },
            { id: 3, name: 'Fast Wifi', icon: 'Wifi', category: 'essentials', available: true },
            { id: 4, name: 'Free parking', icon: 'Car', category: 'essentials', available: true },
            { id: 5, name: 'Fully equipped kitchen', icon: 'ChefHat', category: 'essentials', available: true },
            { id: 6, name: 'Patio or balcony', icon: 'Trees', category: 'features', available: true },
            { id: 7, name: 'EV charger', icon: 'BatteryCharging', category: 'features', available: true },
        ],
        reviews: [
            {
                id: 1,
                author: 'Alex',
                avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
                rating: 5,
                date: 'October 2023',
                comment:
                    'Absolutely stunning place! The focus on sustainability was inspiring, and the cabin itself was incredibly comfortable. Highly recommend!',
            },
            {
                id: 2,
                author: 'Jessica',
                avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
                rating: 5,
                date: 'September 2023',
                comment:
                    'A peaceful retreat. The Mojave desert sounds are so relaxing. The host, Sarah, was very responsive and provided great local tips.',
            },
        ],
        host: {
            id: 1,
            name: 'Sarah',
            avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
            isSuperhost: true,
            responseTime: 'within an hour',
            yearsHosting: 4,
            verified: true,
        },
        latitude: 34.1333,
        longitude: -116.3131,
        highlights: [
            {
                icon: 'Award',
                title: 'Sarah is a Superhost',
                description: 'Superhosts are experienced, highly rated hosts.',
            },
            {
                icon: 'Leaf',
                title: 'Eco-Certified Property',
                description: 'This home meets high standards for energy efficiency and sustainability.',
            },
            {
                icon: 'MapPin',
                title: 'Great location',
                description: '100% of recent guests gave the location a 5-star rating.',
            },
        ],
        cleaningFee: 45,
        serviceFee: 93,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-7f28-b0a7-20268578165b',
        title: 'Bamboo Eco-Villa',
        location: 'Bali, Indonesia',
        imageUrl: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800&h=800&fit=crop',
        imageAlt: 'Bamboo eco-villa surrounded by tropical jungle in Bali',
        pricePerNight: 125,
        rating: 4.85,
        dates: 'Nov 5 – 12',
        images: [
            'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=1200&h=800&fit=crop',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
        ],
        description:
            'Immerse yourself in nature at this unique bamboo eco-villa. Located in the lush jungles of Bali, this architecturally stunning home is built entirely from sustainable bamboo. The open-air design allows the tropical breeze to circulate freely, creating a natural and cooling environment.\n\nPerfect for those looking to disconnect and recharge. The villa features a private garden, an outdoor stone tub, and views of the surrounding rice terraces.',
        reviewCount: 156,
        propertyType: 'Entire villa',
        bedrooms: 1,
        bathrooms: 1,
        beds: 1,
        maxGuests: 2,
        amenities: [
            { id: 1, name: 'Tropical Garden', icon: 'Trees', category: 'features', available: true },
            { id: 2, name: 'Outdoor Tub', icon: 'Bath', category: 'features', available: true },
            { id: 3, name: 'Wifi', icon: 'Wifi', category: 'essentials', available: true },
            { id: 4, name: 'Breakfast included', icon: 'Coffee', category: 'essentials', available: true },
        ],
        reviews: [
            {
                id: 1,
                author: 'Michael',
                avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
                rating: 5,
                date: 'February 2024',
                comment: 'Incredible experience! Living in a bamboo house was a dream come true. The jungle sounds at night are magical.',
            },
        ],
        host: {
            id: 2,
            name: 'Made',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
            isSuperhost: true,
            responseTime: 'within a few hours',
            yearsHosting: 6,
            verified: true,
        },
        latitude: -8.4095,
        longitude: 115.1889,
        highlights: [
            {
                icon: 'Award',
                title: 'Made is a Superhost',
                description: 'Superhosts are experienced, highly rated hosts.',
            },
            {
                icon: 'Leaf',
                title: 'Sustainable Architecture',
                description: 'Built entirely with locally sourced bamboo.',
            },
        ],
        cleaningFee: 35,
        serviceFee: 52,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-7933-9f87-6e47f4f601b0',
        title: 'Jungle Sanctuary',
        location: 'Tulum, Mexico',
        imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=800&fit=crop',
        imageAlt: 'Modern jungle sanctuary structure in Tulum Mexico',
        pricePerNight: 310,
        rating: 5.0,
        dates: 'Dec 10 – 17',
        images: [
            'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&h=800&fit=crop',
            'https://images.unsplash.com/photo-1549294413-26f195200c16?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
        ],
        description:
            'Discover serenity at our Jungle Sanctuary in Tulum. This architecturally unique home is designed to blend seamlessly with the vibrant Mexican jungle, offering privacy, luxury, and a deep connection with nature.',
        reviewCount: 42,
        propertyType: 'Entire house',
        bedrooms: 3,
        bathrooms: 2,
        beds: 3,
        maxGuests: 6,
        amenities: [
            { id: 1, name: 'Private Pool', icon: 'Waves', category: 'features', available: true },
            { id: 2, name: 'Fast Wifi', icon: 'Wifi', category: 'essentials', available: true },
            { id: 3, name: 'Air conditioning', icon: 'Snowflake', category: 'features', available: true },
        ],
        reviews: [],
        host: {
            id: 3,
            name: 'Ana',
            avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
            isSuperhost: true,
            responseTime: 'within a day',
            yearsHosting: 2,
            verified: true,
        },
        latitude: 20.2114,
        longitude: -87.4654,
        highlights: [],
        cleaningFee: 60,
        serviceFee: 85,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-7d2d-a2f1-6e47f4f601b1',
        title: 'Forest bathing retreat',
        location: 'Portland, Oregon',
        imageUrl: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=800&fit=crop',
        imageAlt: 'Cozy cabin in the woods of Portland Oregon',
        pricePerNight: 180,
        rating: 4.92,
        dates: 'Nov 15 – 20',
        images: [
            'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=800&fit=crop',
            'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&h=600&fit=crop',
        ],
        description: 'Immerse yourself in the healing power of nature at our Forest Bathing Retreat near Portland.',
        reviewCount: 88,
        propertyType: 'Entire cabin',
        bedrooms: 2,
        bathrooms: 1,
        beds: 2,
        maxGuests: 4,
        amenities: [],
        reviews: [],
        host: {
            id: 4,
            name: 'John',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
            isSuperhost: false,
            responseTime: 'within an hour',
            yearsHosting: 3,
            verified: true,
        },
        latitude: 45.5152,
        longitude: -122.6784,
        highlights: [],
        cleaningFee: 40,
        serviceFee: 55,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-7e2e-b3f2-6e47f4f601b2',
        title: 'Off-grid beach house',
        location: 'Maui, Hawaii',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=800&fit=crop',
        imageAlt: 'Beach house with ocean view in Maui Hawaii',
        pricePerNight: 450,
        rating: 4.99,
        dates: 'Jan 5 – 12',
        images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop'],
        description: 'Stunning off-grid beach house with breathtaking ocean views in Maui.',
        reviewCount: 31,
        propertyType: 'Entire house',
        bedrooms: 3,
        bathrooms: 2,
        beds: 3,
        maxGuests: 6,
        amenities: [],
        reviews: [],
        host: {
            id: 5,
            name: 'Kai',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
            isSuperhost: true,
            responseTime: 'within an hour',
            yearsHosting: 5,
            verified: true,
        },
        latitude: 20.7984,
        longitude: -156.3319,
        highlights: [],
        cleaningFee: 80,
        serviceFee: 110,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-7f2f-c4f3-6e47f4f601b3',
        title: 'Zero-emission chalet',
        location: 'Aspen, Colorado',
        imageUrl: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&h=800&fit=crop',
        imageAlt: 'Snow covered modern cabin in Aspen Colorado',
        pricePerNight: 620,
        rating: 4.88,
        dates: 'Dec 20 – 27',
        images: ['https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop'],
        description: 'Luxurious zero-emission chalet perfect for ski enthusiasts in Aspen.',
        reviewCount: 15,
        propertyType: 'Entire cabin',
        bedrooms: 4,
        bathrooms: 3,
        beds: 5,
        maxGuests: 10,
        amenities: [],
        reviews: [],
        host: {
            id: 6,
            name: 'Erik',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
            isSuperhost: true,
            responseTime: 'within few hours',
            yearsHosting: 8,
            verified: true,
        },
        latitude: 39.1911,
        longitude: -106.8175,
        highlights: [],
        cleaningFee: 120,
        serviceFee: 150,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-8030-d5f4-6e47f4f601b4',
        title: 'Glamping under stars',
        location: 'Sedona, Arizona',
        imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=800&fit=crop',
        imageAlt: 'Red rock landscape view from a glamping tent in Sedona Arizona',
        pricePerNight: 215,
        rating: 4.95,
        dates: 'Nov 2 – 7',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&h=800&fit=crop'],
        description: 'Unique glamping experience under the beautiful Sedona stars.',
        reviewCount: 124,
        propertyType: 'Entire tent',
        bedrooms: 1,
        bathrooms: 0.5,
        beds: 1,
        maxGuests: 2,
        amenities: [],
        reviews: [],
        host: {
            id: 7,
            name: 'Cody',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
            isSuperhost: false,
            responseTime: 'within few hours',
            yearsHosting: 1,
            verified: true,
        },
        latitude: 34.8697,
        longitude: -111.7601,
        highlights: [],
        cleaningFee: 25,
        serviceFee: 35,
        ecoCertified: true,
    },
    {
        id: '0194d3c4-9c02-8131-e6f5-6e47f4f601b5',
        title: 'Sustainable tiny home',
        location: 'Vancouver, Canada',
        imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=800&fit=crop',
        imageAlt: 'Lakeside cabin with mountain view in Vancouver Canada',
        pricePerNight: 145,
        rating: 4.9,
        dates: 'Oct 28 – Nov 4',
        images: ['https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=1200&h=800&fit=crop'],
        description: 'Eco-friendly tiny home with stunning lake and mountain views in Vancouver.',
        reviewCount: 56,
        propertyType: 'Entire house',
        bedrooms: 1,
        bathrooms: 1,
        beds: 1,
        maxGuests: 2,
        amenities: [],
        reviews: [],
        host: {
            id: 8,
            name: 'Chloe',
            avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
            isSuperhost: true,
            responseTime: 'within few minutes',
            yearsHosting: 4,
            verified: true,
        },
        latitude: 49.2827,
        longitude: -123.1207,
        highlights: [],
        cleaningFee: 30,
        serviceFee: 42,
        ecoCertified: true,
    },
];

export function getPropertyById(id: string): PropertyDetail | undefined {
    return mockPropertyDetails.find((property) => property.id === id);
}

export function getAllProperties(): PropertyDetail[] {
    return mockPropertyDetails;
}

export function calculateTotalPrice(pricePerNight: number, nights: number, cleaningFee: number, serviceFee: number) {
    const subtotal = pricePerNight * nights;
    const total = subtotal + cleaningFee + serviceFee;
    return { subtotal, cleaningFee, serviceFee, total, nights };
}
